library(tidyverse)
library(magrittr)

specialty <- c("Cardiology (invasive)", "Cardiology (non-invasive)", 
"Cardiovascular surgery", "Family practice", "Gastroenterology", "General Surgery",
"Hematology/Oncology", "Internal Medicine", "Nephrology", "Neurology", "Neurosurgery", "Ob/Gyn", "Ophthalmology",
"Orthopedic surgery", "Otolaryngology", "Pediatrics","Psychiatry", "Pulmonology", "Urology")
average_revenue <- as.numeric(c(3.5, 2.3, 3.7, 2.1, 3.0, 2.7, 2.9, 2.7,
                     1.8,2.1,3.4,2.0,1.4,3.3,1.9,1.6,1.8,2.4,2.2))
average_salary <- c(.59, .427, .425, .241,  .487,.35, 
                     .425,.261,.272,.301,.687,.324,.3,.533,.405,.230,.261, .418,.386)

data <- data.frame(specialty, average_revenue, average_salary) %>% 
  mutate(pct_rev = round(average_salary*100/average_revenue, digits =2)) %>% 
  arrange(desc(pct_rev))

data

#simple version

data %>% 
  ggplot(aes(x=specialty, y= pct_rev, fill = pct_rev)) +
  geom_bar() 

#fix stat in geom_bar
data %>% 
  ggplot(aes(x=specialty, y= pct_rev, fill = pct_rev)) +
  geom_bar(stat = "identity") 

# flip the coordinates - make this the last line
# fill in above NULL with other commands
data %>% 
  ggplot(aes(x=specialty, y= pct_rev, fill = pct_rev)) +
  geom_bar(stat = "identity") +
  NULL +
  coord_flip()

# put values on bars
data %>% 
  ggplot(aes(x=specialty, y= pct_rev, fill = pct_rev)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = pct_rev), hjust =-0.1) +
  NULL +
  coord_flip()

#  make graph a little wider to accomodate values
data %>% 
  ggplot(aes(x=specialty, y= pct_rev, fill = pct_rev)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = pct_rev), hjust =-0.1) +
  ylim(0,22.8) +
  NULL +
  coord_flip()


#  customize colors, remove legend
data %>% 
  ggplot(aes(x=specialty, y= pct_rev, fill = pct_rev)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = pct_rev), hjust =-0.1) +
  ylim(0,22.5) +
  scale_fill_viridis_c(guide = "none") +
  NULL +
  coord_flip()

# let's think more about colors
# what color words do we use to talk about money and revenue?
# in the black, in the red for profit and loss
# green for money
# you could imagine a gradient from red to black,
# but no one is actually in the red here.
# just varying amounts of salary
# we also need a continuous gradient (not discrete)
# for this continuous variable pct_rev

# so let's go with a gradient from light green to dark green

data %>% 
  ggplot(aes(x=specialty, y= pct_rev, fill = pct_rev)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = pct_rev), hjust =-0.1) +
  ylim(0,22.8) +
  scale_fill_gradient(low = "lightgreen", high = "darkgreen", guide = "none") +
  NULL +
  coord_flip()



#  reorder specialties by pct_rev
data %>% 
  ggplot(aes(x=fct_reorder(specialty, pct_rev), y= pct_rev, fill = pct_rev)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = pct_rev), hjust =-0.1) +
  ylim(0,22.8) +
  scale_fill_gradient(low = "lightgreen", high = "darkgreen", guide = "none") +
  NULL +
  coord_flip()

# add nice labels and theme (bigger base font), take out NULL
data %>% 
  ggplot(aes(x=fct_reorder(specialty, pct_rev), y= pct_rev, fill = pct_rev)) +
  geom_bar(stat="identity") +
  geom_text(aes(label = pct_rev), hjust =-0.1) +
  ylim(0,22.8) +
  scale_fill_gradient(low = "lightgreen", high = "darkgreen", guide = "none") +
  labs(title = "Is the Problem with Primary Care Poor Negotiating Skills?",
       subtitle = "Salary as Percent of Revenue Generated by Specialty",
       x = "Specialty",
       y = "Percent of Revenue Generated",
       caption = "Data from Merritt-Hawkins survey,
       as published in Axios, Caitlin Owens, May 14, 2019") +
  theme_bw(base_size = 14) +
  coord_flip()
                     
# now do this with tennis stars and Grand Slam wins
# From Tidy Tuesday

grand_slams <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-04-09/grand_slams.csv")

winners <- grand_slams %>% group_by(name) %>% tally(sort=TRUE) %>% top_n(15)

# to do for winners:
# make a bar plot with x= name, y = n titles won
# remember to use stat="identity"
# add a coord_flip at the end
# reorder by n
# add value labels
# pick meaningful fill colors
# remove legend
# fix width of y limits if needed
# pick a nice theme, adjust base size
# add nice labels

winners %>% 
  ggplot(aes(x=fct_reorder(name, n), y= n, fill = n)) +
  geom_bar(stat="identity") +
  geom_text(aes(label = n), hjust =-0.1) +
  geom_text(aes(label = name, y=0.2), hjust =0) +
  ylim(0,23.5) +
  scale_fill_gradient(low = "darkgoldenrod", high = "gold", guide = "none") +
  labs(title = "Grand Slam Winners",
       subtitle = "Top Lifetime Winners of Major Tournaments",
       x = "",
       y = "Grand Slam Titles Won",
       caption = "Data from TidyTuesday") +
  theme_bw(base_size = 14) +
  theme(axis.text.y  = element_blank(),
        axis.ticks.y = element_blank()) +
  coord_flip()
